### PR TITLE
Clone data

### PR DESCRIPTION
**Pull request by gareththegeek**
#85

### CODE REVIEW

**Comment by dougajmcdonald** [comment]
Looks good but do we need a clone library with Object.assign or the object spread operator?

**Comment by gareththegeek** [comment]
Do any of these alternatives perform deep clone?

**Comment by dougajmcdonald** [comment]
They do not, my bad!

**Comment by gareththegeek** [comment]
We can probably use `Object.assign` instead of `_.clone` though because it is a shallow clone.  I'll raise a task to remove underscore from the library, I don't think we need it now.

**Pull request merged**
